# This is our new experiment file
# Please note that you may override this settings in experiment configuration file
declarations: 
  net: 
    body: 
      - dense: [40,"tanh"]    
      - dense: [1,"sigmoid"]
  preprocess: 
    #Sequence of preprocesing operations  
callbacks: #put your callbacks here
architecture: net
optimizer: adam
lr: 0.0001
batch: 10
testSplit: 0.2
folds_count: 3
metrics: [binary_accuracy, macro_f1  ]
primary_metric: binary_accuracy 
stages:
  - epochs: 50
dataset: #You need to feel it
  getData: []
loss: binary_crossentropy